spring.application.name=OrderService

server.port=8082

# PostgreSQL
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/order_db
spring.datasource.username=postgres.werpplzzkswkbujepxcq
spring.datasource.password=GatugutaKariuki

spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate ? auto-creates tables on startup
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Actuator endpoints
management.endpoints.web.exposure.include=health,info,env
management.endpoint.health.show-details=when-authorized

# Logging
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.kariioke.inventoryservice=DEBUG

# Eureka
#eureka.client.service-url.defaultZone=http://localhost:9000/eureka/
#eureka.instance.prefer-ip-address=true
